### ISSUE TITLE
1Password passkey causes Illegal Invocation error 

### ISSUE THREAD

**Issue by charlesjiang-greengate** [aws-samples/amazon-cognito-passwordless-auth#94] opened 2023-10-02 03:09 UTC
1Password passkey implementation intercepts webauthn call and replace it with its own implementation in 1Password Chrome extension.

The below line in  https://github.com/aws-samples/amazon-cognito-passwordless-auth/blob/1023e1ef4d2f7eb6b0943315822cecf57f0591d8/client/fido2.ts#L105 causes `Uncaught TypeError: Illegal invocation`. which results in `Illegal invocation` shown in the UI when registering fido2 credential. 

```
    debug?.("Created credential:", {
        credential,
        getTransports: response.getTransports?.(),
        getAuthenticatorData: response.getAuthenticatorData?.(),
        getPublicKey: response.getPublicKey?.(),
        getPublicKeyAlgorithm: response.getPublicKeyAlgorithm?.(),
    });
```

**Comment by ottokruse** [comment] 2023-10-02 07:27
Thanks for the report.

This might be better directed at 1Password potentially though?

I don't use 1Password and can't reproduce this but let's try to see if we can locate and fix it with your help.

Question, how did you confgure the lib, what value are you using for `debug`?

`Illegal invocation` maybe caused by to the destructuring of `response` (from `credential.response`, maybe 1Password proxies it). Have a try changing our code directly inside your node_modules to:

```javascript
debug?.("Created credential:", {
    credential,
    getTransports: credential.response.getTransports?.(), // `credential.response` instead of `response`
    getAuthenticatorData: credential.response.getAuthenticatorData?.(), // `credential.response` instead of `response`
    getPublicKey: credential.response.getPublicKey?.(), // `credential.response` instead of `response`
    getPublicKeyAlgorithm: credential.response.getPublicKeyAlgorithm?.(), // `credential.response` instead of `response`
});
```

Or it's because `debug` doesn't work like that and you need to call configure differently:

Do:

```js
Passwordless.configure({
  ...,
  debug: console.debug.bind(console),
});
```

Instead of:

```js
Passwordless.configure({
  ...,
  debug: console.debug,
});
```

(But there's other debug calls that you'd have run into earlier then so I doubt that is the issue.)

**Comment by charlesjiang-greengate** [comment] 2023-10-02 07:35
Hi @ottokruse , thanks for coming back to you. I think  you are correct on this one, that this is likely to be caused by implementation bug with 1Password chrome extension.  I will raise this issue with 1Password to see if they can fix it on their end.  

debug is currently the default configuration which is `debug: console.debug`, I will give your suggestion a try and come back to you on this.

**Comment by charlesjiang-greengate** [comment] 2023-10-02 07:53
Justing reporting back:

`credential.response.getAuthenticatorData()` still returns the same error `Uncaught TypeError: Illegal invocation`.

Changing to `  debug: console.debug.bind(console),` also didn't help.  

Using debug console, I can see the following

![image](https://github.com/aws-samples/amazon-cognito-passwordless-auth/assets/122828932/6262b068-7962-4945-bc9d-c5b424dd4267)

**Comment by charlesjiang-greengate** [comment] 2023-10-02 08:02
This seems to be an [existing issue](https://1password.community/discussion/142554/passkey-implementation-issue-illegal-invocation) someone has just raised with 1Password as well.  

I am not sure if it is within the spec to be able to call `getPublicKey()` etc.

**Comment by ottokruse** [comment] 2023-10-02 08:13
We only call that method if it's not `null` or `undefined` in which case it should work (as per spec: https://www.w3.org/TR/webauthn-2/#dom-authenticatorattestationresponse-getpublickey)

So yes this looks like an issue for 1Password

**Comment by charlesjiang-greengate** [comment] 2023-10-02 08:15
Thank you very much looking into this issue.  I will try to chase it up on 1Password's end.

**Comment by ottokruse** [comment] 2024-01-12 11:18
Any update on this issue from 1Password side @charlesjiang-greengate ?

I'm inclined to close the issue here.

**Comment by charlesjiang-greengate** [comment] 2024-01-12 18:55
Please close this issue. Fault is not with this library here. 

1Password has been unresponsive on this issue

**Closed** 2024-01-12 19:34 UTC

**Comment by maccuaa** [comment] 2024-12-17 22:02
Unrelated to AWS Coginto, but I ended up here after encountering an Illegal Invocation error while logging in to Oracle Cloud using a passkey stored in 1Password.

If anyone happens to stumble here like I did, here's how I got around the error:

1. Open the browser developer tools and put a breakpoint on this line:

    ![image](https://github.com/user-attachments/assets/7a49ac58-9833-48c0-8be8-585067730f42)

1. There's something in the PublicKeyCredential object that's returned by 1Password that causes the serialization method to throw an Illegal Invokation error. You can tell this by evaluating

    ```js
    JSON.stringify(s, null, 2);
    ```

    ![image](https://github.com/user-attachments/assets/c0c3f33d-8841-41bd-9e78-4a2d7e38045e)

1. Re-assign the variable by running the following snippet. This will drop the problematic parts of the JSON.

    ```js
    s = { ...s }
    ``` 

1. Press the "play" button to continue the execution and login should succeed.

**Comment by Tvangeste** [comment] 2024-12-18 03:40
@maccuaa , I am in the same boat, and today was the day I broke up and decided to figure out what's wrong with 1Password and Oracle Cloud, and your post gave me some hints. :)

So, here's what happens:
* Chrome 129 implemented **PublicKeyCredential**.toJSON()
* mfa-auth-fido-authenticator.js, used in Oracle Cloud, tries to serialize the **PublicKeyCredential**, via JSON.stringify(credential, replacerFunction, 2).
* The first thing JSON.stringify()  does is checks if the PublicKeyCredential object has toJSON(), and if it is present, the method is being invoked.
* In Chrome 128 and prior, the credential had no toJSON() and everything worked just fine.
* In Chrome 129 there is now PublicKeyCredential.toJSON(), but on the object, provided by 1Password, this method just fails with..., yes, Invocation Error! :)

So, the easiest way to fix this is to remove the PublicKeyCredential.toJSON() from our object. And I use Chrome's local overrides feature to automate this fix and FINALLY get it work as intended!

It looks like 1Password's implementation does not have the proper toJSON(), and that's the root of our problem.

**Comment by ottokruse** [comment] 2024-12-18 07:13
Wow guys! Nice digging

**Comment by ottokruse** [comment] 2025-07-17 06:05
@altmind it's likely not this repo at fault though? This is not the right ticket to bump
