### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by sholtomaud** [aws-samples/amazon-cognito-passwordless-auth#219] opened 2024-12-01 06:25 UTC
Given all the open and unresolved issues. Can we call this repo dead and archive it?

**Comment by ottokruse** [comment] 2024-12-02 20:48
Shouldn't be any blocking issues open. Most (all) open tickets are questions and feature requests! We haven't been very active in tidying the issue list.

Cognito has native Passwordless support now and that should be preferred over this lib as explained at the top of the README. If you still need to implement custom auth flows, this repo should be a good reference and get you going way faster than coding from scratch. And it can also still work out of the box for you without customizing.

**Comment by sholtomaud** [comment] 2024-12-03 09:51
since Cognito has native Passwordless support now and that should be preferred over this lib then this lib should probs be deprecated. 

Also, the deplyment fails because the Lambda role doesn't have SES permissions.

**Comment by ottokruse** [comment] 2024-12-03 16:05
> since Cognito has native Passwordless support now and that should be preferred over this lib then this lib should probs be deprecated.

There are specific scenario's where this library may still be considered (eg because it supports some features that are not part of Cognito currently yet) and they are listed out at the top of the README:

- It supports usernameless FIDO2 sign-in (using discoverable credentials)
- It gives you full control of the FIDO2 parameters that are used for the authentication. For example to turn on extensions (such as credProps), or to allow credentials that's don't require `userVerification` but only user presence.
- This solution works in the lowest Cognito pricing tier.
- Magic links and SMS based Step-Up auth are not yet natively available and this solution shows how to do it.
- Lastly this solution can be used as a demonstration of how FIDO2 works; it may be helpful to be able to look under the hood.

> Also, the deplyment fails because the Lambda role doesn't have SES permissions.

Can you provide some more information and steps to reproduce, and we'll look into it.

**Comment by sholtomaud** [comment] 2024-12-06 01:24
BTW @ottokruse why did you roll your own s3deploy, and not just implement a cdk codepipeline?

**Comment by ottokruse** [comment] 2024-12-07 19:21
Wanted tighter control of cache headers.

**Comment by ottokruse** [comment] 2024-12-09 16:04
> yeah you can't do the first email magiclink to get the user signed in.

> I can't remember which of your Lambdas doesn't have sufficient permissions to use SES, do a fresh install and you should have the same issue. I put SES full access on all the Lambdas to get it working in dev.

Just did a fresh clone of this repo, deployed the end-to-end-example again. Worked like a charm, was ble to get a magic link and sign in, no SES permission issues. Also reviewed the source code again, and I see the SES permissions in there as well.

Will close this issue. Will re-open if you can provide steps to reproduce. Thank you

**Closed by ottokruse** 2024-12-09 16:04 UTC
