### ISSUE TITLE
ERR_PACKAGE_PATH_NOT_EXPORTED on /custom-auth

### ISSUE THREAD

**Issue by GMuirDG** [aws-samples/amazon-cognito-passwordless-auth#90] opened 2023-09-13 13:41 UTC
Hello,

I'm following your basic usage guide and it's going great! Everything is working as expected until I try some customisation.

Trying this [read me](https://github.com/aws-samples/amazon-cognito-passwordless-auth/blob/main/CUSTOMIZE-AUTH.md#1-create-your-own-lambda-function-using-this-library-and-call-configure) in order to customise the magic link email's html.

However I'm running into a node error when I try to deploy my stack:

`Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './custom-auth' is not defined by "exports" in /Users/******/Documents/GitHub/my-repo/node_modules/amazon-cognito-passwordless-auth/package.json
    at new NodeError (node:internal/errors:399:5)
    at exportsNotFound (node:internal/modules/esm/resolve:361:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:641:13)
    at resolveExports (node:internal/modules/cjs/loader:565:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:634:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1061:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/Users/******/Documents/GitHub/my-repo/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}`

I'm using node: 18.15.0, amazon-cognito-passwordless-auth: 0.7.1

The magic link import looks like this: 
`import { magicLink } from 'amazon-cognito-passwordless-auth/custom-auth'
`

Have I missed something obvious here?

Edit:

After digging around there is a difference between the exports in the main `package.json` file.
The cdk module, which was working fine, has a default key like this:
`"./cdk": {
      "default": "./dist/cdk/lib/cognito-passwordless.js",
      "types": "./cdk.d.ts"
    }`
    
Whereas the custom-auth module, which I'm having trouble with, uses an import:
`  "./custom-auth": {
      "import": "./dist/cdk/custom-auth/index.js",
      "types": "./custom-auth/index.d.ts"
    }`
    
Swapping the import for default gets past the `ERR_PACKAGE_PATH_NOT_EXPORTED` error but then runs into an `ERR_REQUIRE_ESM` one.

This might be because there are different compiler option targets? 
[cdk/lib](https://github.com/aws-samples/amazon-cognito-passwordless-auth/blob/main/cdk/lib/tsconfig.json) targets ES2020 while [cdk/custom-auth](https://github.com/aws-samples/amazon-cognito-passwordless-auth/blob/main/cdk/custom-auth/tsconfig.json#L3) targets ES2022

I'm lost though and could use some advice on this! Any help would be amazing

**Comment by ottokruse** [comment] 2023-09-14 19:30
Thanks for your interest in this solution!

Looks like you are compiling your lambda functions as common JS and we expect ESM. But changing import to default as you did should fix that and maybe we should actually change it.

If you compile your function to ESM your problem should be solved. 

Otherwise, give more information on the require ESM error you are seeing?

**Comment by ottokruse** [comment] 2023-09-14 19:31
It's fine by the way that CDK code targets CommonJS and your lambda code targets ESM (it's what we do too and that works fine)

**Comment by GMuirDG** [comment] 2023-09-21 08:50
Thanks for your response. I've tried changing import to default, as well as playing around with different code targets and have had no luck.

I have managed to get custom HTML into the magic link email, but I had to replace the createAuthChallenge lambda with my own. This is essentially a copy pasted version of this package's, but with the html changed.

**Comment by ottokruse** [comment] 2023-09-21 12:56
Ok great. If you can provide a reproducible sample we'll look into this further? Cheers

**Comment by fkwfung** [comment] 2023-10-04 16:48
Thank you @ottokruse for this valuable stack.

I think I am facing the same issue. Trying to customize auth with email template and SES modification, however, the mjs build from CDK for the lambda becomes common JS:
``
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __require = /* @__PURE__ */ ((x) => typeof require !== "undefined" ? require : typeof Proxy !== "undefined" ? new Proxy(x, {
  get: (a, b) => (typeof require !== "undefined" ? require : a)[b]
}) : x)(function(x) {
  if (typeof require !== "undefined")
    return require.apply(this, arguments);
  throw Error('Dynamic require of "' + x + '" is not supported');
});
var __commonJS = (cb, mod) => function __require2() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
``

(Skipping the remaining code)


The way I override is to setting functionProps on Passwordless stack:
``
// Override email content creator
      functionProps: {
        createAuthChallenge: {
          // Override entry, to point to custom email content creator
          entry: join(__dirname, "./custom-email/create_auth_custom_email.ts"),
          memorySize: 256,
          runtime: cdk.aws_lambda.Runtime.NODEJS_18_X,
          architecture: cdk.aws_lambda.Architecture.ARM_64,
          bundling: {
            format: cdk.aws_lambda_nodejs.OutputFormat.ESM,
            esbuildArgs: {
              "--main-fields": "module,main",
            },
            externalModules: ["@aws-sdk/*", "aws-lambda"],
          },
          
          environment: {
            EMAIL_TEMPLATE_TABLE_NAME: emailTemplateTable.tableName,
            QUEUE_URL_SES_SEND_EMAIL: sqsSesQueue.queueUrl,
          },
        },
      },
``

When the auth flow is initiated at Cognito with Magic Link, the lambda will hit the following error:
``
{
    "errorType": "Error",
    "errorMessage": "Dynamic require of \"stream\" is not supported",
    "stack": [
        "Error: Dynamic require of \"stream\" is not supported",
        "    at file:///var/task/index.mjs:12:9",
        "    at node_modules/cbor/lib/commented.js (file:///var/task/index.mjs:2240:18)",
        "    at __require2 (file:///var/task/index.mjs:15:50)",
        "    at node_modules/cbor/lib/cbor.js (file:///var/task/index.mjs:3851:25)",
        "    at __require2 (file:///var/task/index.mjs:15:50)",
        "    at file:///var/task/index.mjs:5626:27",
        "    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)"
    ]
}
``

No luck on changing target build. 
Appreciate if any help / advice on this.
Thanks a lot!

**Comment by ottokruse** [comment] 2023-10-04 20:10
> Thank you @ottokruse for this valuable stack.

Cheers mate! Thanks!

IIRC the `"Dynamic require of \"stream\" is not supported"` can be solved by adding a banner to your bundling options:

```js
bundling: {
  ..., // other bundling options
  banner: "import{createRequire}from 'module';const require=createRequire(import.meta.url);"
}
```

Give that a shot?

**Comment by fkwfung** [comment] 2023-10-05 01:28
@ottokruse  It works after adding the banner!

Now the custom lambda can be triggered at Create Auth with both ``contentCreator`` and ``emailSender``!
Great thanks!

**Comment by ottokruse** [comment] 2023-10-05 07:12
Nice!

**Comment by fkwfung** [comment] 2023-10-05 10:12
Thank you @ottokruse  for your prompt help!

One more question, if we need to use an API Gateway to initiate Magic Link sending, following the current ``Passwordless`` stack. Do you recommend to use send ``AdminInitiateAuthCommand`` then ``AdminRespondToAuthChallengeCommand`` in order to trigger? (It will take a few sec to respond from API Gateway if waiting for whole flow to complete)

**Comment by ottokruse** [comment] 2023-10-05 11:04
I need more info to think along with you. What's the context, why and how do you want to involve API Gateway? Would you mind continuing this in another issue please?

**Comment by tinti** [comment] 2024-01-03 11:38
> > Thank you @ottokruse for this valuable stack.
> 
> Cheers mate! Thanks!
> 
> IIRC the `"Dynamic require of \"stream\" is not supported"` can be solved by adding a banner to your bundling options:
> 
> ```js
> bundling: {
>   ..., // other bundling options
>   banner: "import{createRequire}from 'module';const require=createRequire(import.meta.url);"
> }
> ```
> 
> Give that a shot?

This should be at the docs. It solved my problem too.

**Comment by ottokruse** [comment] 2024-01-03 16:31
Yes we should. Want to send a PR for it @tinti? Guess we should add it here: https://github.com/aws-samples/amazon-cognito-passwordless-auth/blob/main/CUSTOMIZE-AUTH.md

**Comment by tinti** [comment] 2024-01-09 09:21
Yes. Created.

https://github.com/aws-samples/amazon-cognito-passwordless-auth/pull/135

**Comment by ottokruse** [comment] 2024-01-12 11:17
Closing for now

**Closed by ottokruse** 2024-01-12 11:17 UTC
