### ISSUE TITLE
The example don't work corrrectly with Windows Hello through PIN authentication

### ISSUE THREAD

**Issue by cordev-developer** [aws-samples/amazon-cognito-passwordless-auth#169] opened 2024-05-14 06:37 UTC
Ey guys, I've been working with this example since many days ago. I've checked it with my MacBook Pro M2 and the Passkeys works correctly, but when I check it in my windows desktop, when I'm logued through magic link and I can access to the user created in my User Pool (with the email address verified), then I add the windows hello Passkey and it seems it's all ok, but when I have done the logout and I want to loguin through this Passkey, then always the application says that the user is invalid. Maybe this example is not adapted to windows hello yet ?, thanks in advance .

**Comment by ottokruse** [comment] 2024-05-14 07:49
Hi mate. You need to be at least on v0.12.2 for windows to work. What version are you on?

**Comment by ottokruse** [comment] 2024-05-14 09:01
Yes that's what I meant. That version should be good. 

Please paste the full error message here, and any steps to reproduce.

**Comment by cordev-developer** [comment] 2024-05-14 11:48
Ok, today I will give more information about how to reply the behaviour, I would include some screenshot also to give you more details. See you later.

**Comment by ottokruse** [comment] 2024-05-16 04:56
You can ignore those deprecated dependencies. It's because the sample apps contain some dependencies beyond the Passwordless lib. The Passwordless  lib itself should not have deprecated dependencies (it has few deps anyway)

**Comment by ottokruse** [comment] 2024-05-16 04:57
And great that it's working out for you! Thanks for mentioning you like it 👍🏻👍🏻

**Comment by cordev-developer** [comment] 2024-05-16 05:38
Ok ottokruse,

And ok for your comment aobut the deprecated deps, I will follow your recomendation about ignore it.

Have an awesome day ahead.

**Comment by ottokruse** [comment] 2024-05-16 22:04
Cheers mate. Let me know how it goes

**Comment by cordev-developer** [comment] 2024-05-25 06:56
Hi ottokruse,

Hope you are doing well. I've got a question about how is generated de "credentilId" stored in the DynamoDB table, maybe could be the challenge response from authenticator ?. As I see also is transformed in the sort key in the DynamoDB register. I hope this is correct, to find out I have followed the lambda function code of the VerifyAuth lambda. I'm not sure this is correct, can you help me ? Thanks in advance.

**Comment by ottokruse** [comment] 2024-05-25 14:18
Hi mate. The user's authenticator generates credentialId

**Comment by cordev-developer** [comment] 2024-05-25 21:46
Hi ottokruse, thanks for the reply. Ok, as I see in the diagram for registering new FIDO2 Authenticator (https://github.com/aws-samples/amazon-cognito-passwordless-auth/blob/main/FIDO2.md), in what step is it created ? Also, maybe in the step 21 is it in which the credentialID is stored ? Thanks again !

**Comment by ottokruse** [comment] 2024-05-27 20:47
Here mate:

![image](https://github.com/aws-samples/amazon-cognito-passwordless-auth/assets/6275520/01cac0a0-5744-411b-ad97-106290319d93)

**Comment by cordev-developer** [comment] 2024-05-28 08:53
Umm ok, that's interesting, also I suppose after this, finally it's stored in DynamoDB., etc., and asociated with the public key.
On the other hand, I've been working in a Cognito course in Spanish, I will show the FIDO2 example and I though to explain also the Amplify example, etc., Do you know more resources related with FIDO2 and Cognito ?, Thanks in advance.

**Comment by ottokruse** [comment] 2024-05-28 10:52
Storing in DynamoDB is a little later, when we also have collected the Friendly name. In the current diagram it is step 21.

Seen the [YouTube video](https://www.youtube.com/watch?v=hY54Zy-l6hc&themeRefresh=1) and [workshop](https://catalog.workshops.aws/cognito-webauthn-passwordless/en-US) yet? There is also this blog: https://aws.amazon.com/blogs/security/how-to-implement-password-less-authentication-with-amazon-cognito-and-webauthn/

**Comment by cordev-developer** [comment] 2024-05-28 13:26
Hi again, yes I saw the video and visited the workshop and I followed the instructions, only I need to test the possible attack scenarios (I though it was very interesting part). Related to the Github repository your comment I also saw the last week, but I had problemes to execute since it's different from this repositoy, I remember I had problemes related to Node dependencies as it uses Node version 12, what do you think about ?. 
On the other hand, I've been preparing some classes to my course, and hopefully when I have finished I'm preparing another course of Cognito but in English language. thanks again !!

**Comment by ottokruse** [comment] 2024-06-24 08:43
Closing this issue, let me know if there's still anything

**Closed by ottokruse** 2024-06-24 08:43 UTC
